apiVersion: v1
kind: Service
metadata:
  labels:
    app: boilerplate-hapi
  name: boilerplate-hapi
spec:
  ports:
  - name: hapi
    port: 9090
    targetPort: 9090
  selector:
    app: boilerplate-hapi
