apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proton-affiliate-hasura
  name: proton-affiliate-hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proton-affiliate-hasura
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: proton-affiliate-hasura
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - args:
            - graphql-engine
            - serve
            - --enable-console
          envFrom:
            - configMapRef:
                name: proton-affiliate-hasura-config
          image: ${DOCKER_REGISTRY}/${IMAGE_NAME_HASURA}:${VERSION}
          imagePullPolicy: 'IfNotPresent'
          name: 'proton-affiliate-hasura'
          ports:
            - containerPort: 8080
      restartPolicy: Always
