apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proton-affiliate-webapp
  name: proton-affiliate-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proton-affiliate-webapp
  template:
    metadata:
      labels:
        app: proton-affiliate-webapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: ${DOCKER_REGISTRY}/${IMAGE_NAME_WEBAPP}:${VERSION}
          imagePullPolicy: 'Always'
          name: proton-affiliate-webapp
          envFrom:
            - configMapRef:
                name: proton-affiliate-webapp-config
          ports:
            - containerPort: 80
      restartPolicy: Always
